# Generated by Django 3.0.6 on 2020-08-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200806_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
